apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-security-admin-config
data:
  setup.sh: |
    #!/bin/bash
    set -e

    export JAVA_HOME=/usr/share/opensearch/jdk
    export PATH=$PATH:$JAVA_HOME/bin

    chmod +x /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh

    /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh \
      -cacert /usr/share/opensearch/config/certificates/ca/ca.pem \
      -cert /usr/share/opensearch/config/certificates/admin/admin.pem \
      -key /usr/share/opensearch/config/certificates/admin/admin.key \
      -cd /usr/share/opensearch/plugins/opensearch-security/securityconfig \
      -h $os_node -nhnv -icl
