apiVersion: v1
kind: Secret
metadata:
  name: opensearch-cert
type: Opaque
stringData:
  opensearch.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcer0z+Vke+yd7
    rhjTi3z8ic8IU+hPThaMec9u0/7uG6k7wK+D1YPJ0dpXdpp5ichUuI/ISP9hdIc5
    8BrcQYR3jaalDpQQCS129xQOAQ+Knqi8fAA/2rk9oW3wRYOpVGVC7KmqR9PRHJj3
    /9VkZ0QQ8h1LVQgBjFlRy9FLCKSdVH2qRkz0sLMd/iZxLrsNkUPAghAmwG2sVpId
    LHo/nqdQ9D120nVes3xs8frOw7oEGwzMl215nGL9ncZfd4HVcc1f7+dSgUUYBAgO
    COilsG6P+bogdaX5VHXW/a7cs3GVaXrGNVmyxb407N/yFlWLYN4hAiQipp9qrJFH
    1FPH9o9XAgMBAAECggEAFPpXdypMily9VFVouqOOpASNnt4w3MDpQPfrmT4OhTls
    HLieTxxGyL27edJKr1SLaOA9VmqC4jvPDTNlRnX6HlT9LE+iBexVDgfdxmrZ/Il8
    sZgmKGlYQCzuIjIPjpnj4W785/ktKnGdCFJh903o0CTFTJ4frqV0LAUZD+geuYCu
    lZ4moUZYYHlb+rrMdmgzOYEKj2X7F+cOjPRzMHrLYGI5TBsnQmqugLrp4352j31R
    FJRWzGnmNSi6bKz+NdV05SLx5kMaT3/sokShzWynMnrcHTxqDlZOaqff/8Hp8+cW
    G3tlFr2Sz1XbRF1EiZ0ck/JmuJx38eqwR8J4Wsjp4QKBgQDJnOyk/oHt+JIpcU+B
    x9wkC9uvEz3MYVzajS/bzI0rK2WlKpaygU2e8pZsUyxSWjGi0KDlMgoUvOGf3FJS
    v9bcS5vM62So3kxc/oj2+F0kxK5lRyPnu6GPvAec3BWfBPPgaFlHNzKyJAEinNLb
    EfbOTGBf4jmlMW/LCNZC8vNyyQKBgQDGsPay4C9OAlknA0mZKDOIM1S8FpVDeWp3
    DV1KzGdT2D0FFjMnsTo/vva5PpFXwZMmriAKu/vSnyuzNFEY25LSAHYp3l7aCYR/
    0LOD0/K1kai6aypA7cs8UtaGVD4z1G9731wzhTqKjbm49L7RvmvryT1l/gQvAlMH
    jwou+1HhHwKBgF+Yw/C8KRmQaqWx77Qm8zA4WzNZmUzmwaNznMTI6gsVKb42Qnxj
    qU17022LxpFJ6Q09hX0HzBXnNciaLILGKfgM9dQlrXYQ6f6SRplsTKYZiGPHZrQD
    mOjRjH6JMMtVCtpWQDbval9jiRJDcAumKfPJ7UyptRGqLksEZqwaDOtZAoGBAIdo
    4zhVAOgxQYENBIOUmkogcYcd/OvXO2+XdBUd6O2DWVK2JnbOmdwH0S2+Ll+YVSjv
    Unb+VkjcoXOoG/zM5+qm1eEC47HE+sABA9a8A5Uqh8tEba+CYBfkfL9femToSnIp
    bzTNf3Ad1ozuf32CQRqYM3fm/gLrmpp0KYSLUuoRAoGAZUAIHJYpJ9WmuXvks9lf
    JnQ4/ZmrwGXiU6o1sx0IJobOjkyqlAbeOtVjDbBvu/+jWya7V/EaS6NaRuA+l9H2
    CXk/ReW/lb4IC5isRf+xgU+5Q1C526kecyQNwe7FMA2Vgt9Wz9ek0CBFsRdPdUAX
    vm3ENmQF0lqib53mFkF+Y9w=
    -----END PRIVATE KEY-----
  opensearch.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIUY7KRlY6sSPPKW5QC94WityjqHcEwDQYJKoZIhvcNAQEL
    BQAwQTELMAkGA1UEBhMCVU4xCzAJBgNVBAgMAlVOMQswCQYDVQQHDAJVTjELMAkG
    A1UECgwCVU4xCzAJBgNVBAMMAkNBMB4XDTIxMDgyMjE1MTU0N1oXDTIxMDkyMTE1
    MTU0N1owSTELMAkGA1UEBhMCVU4xCzAJBgNVBAgMAlVOMQswCQYDVQQHDAJVTjEL
    MAkGA1UECgwCVU4xEzARBgNVBAMMCm9wZW5zZWFyY2gwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCcer0z+Vke+yd7rhjTi3z8ic8IU+hPThaMec9u0/7u
    G6k7wK+D1YPJ0dpXdpp5ichUuI/ISP9hdIc58BrcQYR3jaalDpQQCS129xQOAQ+K
    nqi8fAA/2rk9oW3wRYOpVGVC7KmqR9PRHJj3/9VkZ0QQ8h1LVQgBjFlRy9FLCKSd
    VH2qRkz0sLMd/iZxLrsNkUPAghAmwG2sVpIdLHo/nqdQ9D120nVes3xs8frOw7oE
    GwzMl215nGL9ncZfd4HVcc1f7+dSgUUYBAgOCOilsG6P+bogdaX5VHXW/a7cs3GV
    aXrGNVmyxb407N/yFlWLYN4hAiQipp9qrJFH1FPH9o9XAgMBAAGjKjAoMCYGA1Ud
    EQQfMB2CCWxvY2FsaG9zdIcEfwAAAYIKb3BlbnNlYXJjaDANBgkqhkiG9w0BAQsF
    AAOCAQEADSDLChkErZRaZlTmERFrVWg+PG+Ggdg7o602JCOM04b7tvYKbr3oxgF5
    ZCPsF4SYFfySXnyEpQiZvMKV+eynMcVD3eFOoeqhoC8rmqAHQe/07CvNklfDBCDB
    UJo/KE9lL2LifNxRGMUuTELazHr7+rCH0HKLkvTnsE4FToVaYc+yF3ZyohAT3lSA
    /87MnyhNYovyaFmhgONVGAso6UWeOG65hmwZCFRnNIqt9DAF/cEILfR61HXgyJwj
    AuGMxr/0N5/bEbVX6XDti+RzIjldCp5njc8Hflq2ODsYkPqVaoWnR+0n6SNpCm9w
    aQksLsT7omeqb3e6ClP5WsubCyiAGA==
    -----END CERTIFICATE-----


